# Your wrangler.toml file should look something like this:
name = "nextjs-d1-drizzle-cloudflare-pages"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# WARNING: When running a production build locally using Wrangler, be aware that the .env file may be omitted. Therefore, ensure that you have the same environment variables in your wrangler.toml file.
# However, you don't have to include Drizzle environment unless you want to access `drizzle-kit` commands in the deployed code.
[vars]

# [[d1_databases]]
# binding = "DB" # i.e. available in your Worker on env.DB
# database_name = "nextjs-d1-drizzle-cloudflare-pages" # When you create your D1 DB, you choose the name
# database_id = "TBA"
# preview_database_id = "DB"

# [env.preview]
# name = "preview"
# [[env.preview.d1_databases]]
# binding = "DB" # i.e. available in your Worker on env.DB
# database_name = "nextjs-d1-drizzle-cloudflare-pages-preview"
# database_id = "TBA"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "d1-riptier-prod-db"
database_id = "c62b775f-a063-4485-b640-9420a232c3d2"
preview_database_id = "DB"

[env.preview]
name = "preview"
[[env.preview.d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "d1-riptier-preview-db"
database_id = "839a0d26-c2e3-4189-80ff-2655fb39d8ef"